export { default as HomePage } from './HomePage';
export { default as PricesPage } from './PricesPage';
export { default as TncPage } from './policy/TncPage';
export { default as TouPage } from './policy/TouPage';
export { default as GdprPage } from './policy/GdprPage';
export { default as Contact } from './Contact';
export { default as About } from './About';
export { default as Functionality } from './Functionality';
export { default as Guides } from './Guides';
